num_main_parties = 2
hub_party_id = 1
debug = true

## Crypto parameters
# Options: PN12QP109, PN13QP218, PN14QP438, PN15QP880, PN16QP1761
# Defined in ckks/params.go in Lattigo library
ckks_params = "PN14QP438"

# MPC parameters
div_sqrt_max_len = 100000 # TODO: currently ignored
mpc_num_threads = 1
mpc_field_size = 256
mpc_data_bits = 60
mpc_frac_bits = 30
mpc_boolean_shares = true

binding_ipaddr = "0.0.0.0"

## Networking parameters
# Party with a smaller ID listens for connection
# Port only needed for the listener
[servers.party0]
ipaddr = "127.0.0.1"
ports  = {party1 = "8020", party2 = "8040", party3 = "8050"}  # Port numbers need to be at least mpc_num_threads apart

[servers.party1]
ipaddr = "127.0.0.1"
ports  = {party2 = "8060", party3 ="8070"}

[servers.party2]
ipaddr = "127.0.0.1"
ports  = {party3 = "8090"}

[servers.party3]
ipaddr = "127.0.0.1"
ports  = {}

