num_main_parties = 2
hub_party_id = 1
debug = true

## Crypto parameters
# Options: PN12QP109, PN13QP218, PN14QP438, PN15QP880, PN16QP1761
# Defined in ckks/params.go in Lattigo library
ckks_params = "PN14QP438"

# MPC parameters
phase = ""
mpc_num_threads = 4
mpc_field_size = 256
mpc_data_bits = 60
mpc_frac_bits = 30
div_sqrt_max_len = 1000000
mpc_boolean_shares = true

## Data dimensions
num_rows = [0, 1252, 1252]
num_columns = 1773

## PCA parameters
iter_per_eigenval = 1
num_pcs_to_remove = 2
num_oversampling = 2
num_power_iters = 10

## Networking parameters
# Party with a smaller ID listens for connection
# Port only needed for the listener

binding_ipaddr = "0.0.0.0" # When establishing a connection, listens on all interfaces
# by default; change to a specific IP address if needed

[servers.party0]
ipaddr = "127.0.0.1"
ports = { party1 = "8020", party2 = "8040" } # Port numbers need to be at least mpc_num_threads apart

[servers.party1]
ipaddr = "127.0.0.1"
ports = { party2 = "8060" }

[servers.party2]
ipaddr = "127.0.0.1"
ports = {}
