num_main_parties = 2
hub_party_id = 1
debug = true
assoc_single_block = false

## Crypto parameters
# Options: PN12QP109, PN13QP218, PN14QP438, PN15QP880, PN16QP1761
# Defined in ckks/params.go in Lattigo library
ckks_params = "PN14QP438"

# MPC parameters
div_sqrt_max_len = 1000000
mpc_num_threads = 12
#mpc_field_size = 128
#mpc_data_bits = 90
#mpc_frac_bits = 30
mpc_field_size = 256
mpc_data_bits = 60
mpc_frac_bits = 30
mpc_boolean_shares = true

## Data dimensions
num_inds = [0, 9178, 9178]
num_snps = 612794
num_covs = 10
cov_all_ones = false

## Input file options (supports "blocks" or "pgen")
geno_file_format = "blocks"
use_precomputed_geno_count = false

## Assoc test parameters
use_cached_combined_q = false
blocks_for_assoc_test = [] # tests all if empty
pgen_batch_nsnp = 8192 # only used if geno_file_format = pgen

## Quality control parameters
use_cached_qc = false
skip_qc = false
imiss_ub = 0.05
het_lb = 0.25
het_ub = 0.30
gmiss = 0.1
maf_lb = 0.1
hwe_ub = 28.374
snp_dist_thres = 100000

## PCA parameters
use_cached_pca = false
skip_pca = false
iter_per_eigenval = 5
num_pcs_to_remove = 5
num_oversampling = 10
num_power_iters = 2

## Networking parameters
# Party with a smaller ID listens for connection
# Port only needed for the listener
[servers.party0]
ipaddr = "10.150.15.216" #"127.0.0.1" #"10.150.0.16"
ports  = {party1 = "8020", party2 = "8040"}

[servers.party1]
ipaddr = "10.150.15.217" #"127.0.0.1" #"10.150.0.24"
ports  = {party2 = "8060"}

[servers.party2]
ipaddr = "10.150.15.218" #"127.0.0.1" #"10.150.0.26"
ports  = {}